dockerizando el proyecto
Trycatch-tv/ValidadorBootcamp-backend pull request #63
Opened 2024-01-15 03:08 UTC by tartabullroberto

2024-01-15 03:17 UTC, tartabullroberto reviewed
OK!

2024-01-21 03:30 UTC, Nexeum requested changes
Te deje unas recomendaciones en cuanto al dockerfile - docker compose

2024-01-21 03:30 UTC, Nexeum commented on Dockerfile
> +RUN npm install
1. npm ci en lugar de npm install. Esto asegurará que se instalen las dependencias exactas.
2. npm audit para buscar vulnerabilidades
3. npm cache clean --force para limpiar la caché de npm y reducir el tamaño de la imagen

```
RUN npm ci && \
    npm audit && \
    npm cache clean --force
```

2024-01-21 03:30 UTC, Nexeum commented on docker-compose.yml
> +    links:
En lugar de utilizar "links", utiliza la configuración de"networks" para conectar los contenedores. Este es un enfoque más moderno y proporciona un mejor aislamiento entre contenedores

2024-01-29 03:03 UTC, merged