feat: :sparkles: Agregar middleware UserAuthorizationMiddleware
Trycatch-tv/ValidadorBootcamp-backend pull request #76
Opened 2024-04-30 23:05 UTC by J4F3ET

- [ ]  Implementacion de JWT
    - [x] Implementación de UserAuthorizationMiddleware
      - Se creo la carpeta "middleware" y dentro se agrego "user"
      - Configuro middleware para que lo use solo "user/list" pero **no su logica**
  - [x] Agregar UnauthorizedResponse para documentarlo en  Swager
  - [ ]  Proteger endpoint "users/list"
  - [ ] Singin 
    - [ ]  implementar Cookie

2024-04-30 23:08 UTC, J4F3ET commented
mi primera chamba 😆

2024-05-11 04:18 UTC, judlup requested changes

2024-05-11 04:18 UTC, judlup commented on src/middlewares/users/authorization.middleware.ts
>    private async extractTokenFromHeader(
Apreciado señor Tinky, esta función se va a potencialmente reutilizar en otros momentos, por lo tanto es mejor ubicarla en un archivo global dentro de la carpeta utils -> src/utils/jwt/jwt.utils.ts

2024-05-11 04:18 UTC, judlup commented on src/middlewares/users/authorization.middleware.ts
> +        await this.jwtService.verifyAsync(token, {
Apreciado señor Tinky, esta función potencialmente se va a reutilizar a futuro, por lo tanto sería conveniente moverla a la ruta global de utils -> src/utils/jwt/jwt.utils.ts con todas las funciones que se vayan a utilizar de este servicio.

2024-08-03 01:41 UTC, judlup commented
@J4F3ET señor tinky este pull request está completo o falta algo para poder hacer el merge?

2024-08-11 01:44 UTC, closed without merging